[package]
name = "logicgates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slotmap = "1.0.6"
symtern = "0.1.0"
nu-ansi-term = "0.46.0"
sfml = "0.20.0"
